-- 관리자계정에서 
CREATE USER c##jdbc IDENTIFIED BY jdbc;
GRANT CONNECT, RESOURCE TO c##jdbc;
ALTER USER c##jdbc QUOTA 1024M ON USERS;

GRANT CREATE VIEW TO c##jdbc;

-- 사번 자동 발생 시퀀스 생성
CREATE SEQUENCE SEQ_EMPID
START WITH 211
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;
